/**
 * tailwind.config.js
 * Tema de diseño de ArtClash Pro (colores, tipografías, espaciados y tamaños de texto).
 * Es el mismo tema que venía embebido en los HTML originales (<script id="tailwind-config">),
 * movido aquí para que Tailwind lo compile en lugar de usar el CDN.
 */

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#ffb690',
        'surface-bright': '#393939',
        'surface-variant': '#353535',
        'surface-container-low': '#1b1c1c',
        'on-tertiary': '#552100',
        secondary: '#c6c6c7',
        'surface-container-lowest': '#0e0e0e',
        primary: '#ffb693',
        'on-primary': '#561f00',
        'surface-container': '#1f2020',
        'on-secondary-container': '#b4b5b5',
        'on-background': '#e4e2e1',
        'error-container': '#93000a',
        'on-primary-fixed-variant': '#7a3000',
        'inverse-surface': '#e4e2e1',
        'primary-fixed': '#ffdbcc',
        'surface-container-high': '#2a2a2a',
        'surface-tint': '#ffb693',
        'tertiary-fixed': '#ffdbca',
        'on-secondary': '#2f3131',
        'on-primary-container': '#572000',
        'secondary-container': '#454747',
        'on-tertiary-container': '#562100',
        outline: '#a98a7d',
        'on-surface': '#e4e2e1',
        'inverse-primary': '#a04100',
        'secondary-fixed': '#e2e2e2',
        'inverse-on-surface': '#303030',
        'on-secondary-fixed': '#1a1c1c',
        'outline-variant': '#5a4136',
        error: '#ffb4ab',
        'on-tertiary-fixed': '#341100',
        background: '#131313',
        'surface-dim': '#131313',
        'primary-container': '#ff6b00',
        'on-tertiary-fixed-variant': '#783200',
        'on-error-container': '#ffdad6',
        'tertiary-container': '#f77214',
        'on-error': '#690005',
        tertiary: '#ffb690',
        'on-surface-variant': '#e2bfb0',
        surface: '#131313',
        'surface-container-highest': '#353535',
        'on-secondary-fixed-variant': '#454747',
        'primary-fixed-dim': '#ffb693',
        'secondary-fixed-dim': '#c6c6c7',
        'on-primary-fixed': '#351000',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '1.25rem',
        margin: '3rem',
        gutter: '1.5rem',
        'space-xl': '2.5rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-lg': '1.5rem',
        'gutter-mobile': '1rem',
        'space-md': '1rem',
      },
      fontFamily: {
        'headline-sm': ['Space Grotesk'],
        'title-md': ['Work Sans'],
        'title-lg': ['Space Grotesk'],
        'body-sm': ['Work Sans'],
        'display-mobile': ['Space Grotesk'],
        'headline-md': ['Space Grotesk'],
        'headline-lg-mobile': ['Space Grotesk'],
        'body-md': ['Work Sans'],
        display: ['Space Grotesk'],
        'body-lg': ['Work Sans'],
        'headline-lg': ['Space Grotesk'],
        'label-md': ['JetBrains Mono'],
        'label-sm': ['JetBrains Mono'],
        'label-lg': ['JetBrains Mono'],
      },
      fontSize: {
        'headline-sm': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '22px', fontWeight: '600' }],
        'title-lg': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'display-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        display: ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '500' }],
        'label-lg': ['14px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
